Change update all to update self plugins
zap-zsh/zap pull request #152
Opened 2023-05-14 17:22 UTC by 5c077m4n

In this PR I added the `plugins` option to the `update` command to update only the plugins and changed the `all` option to update all parts (self + plugins)

2023-05-14 21:01 UTC, mamaraddio requested changes
Nice, just add the information about the new option in the README.md

2023-05-15 05:19 UTC, 5c077m4n commented
> Nice, just add the information about the new option in the README.md

Done 😊

2023-05-15 09:12 UTC, wintermi approved these changes

2023-05-15 09:13 UTC, wintermi approved these changes

2023-05-15 10:39 UTC, mamaraddio requested changes
Please fix what I suggested to ensure clarity in `README.md` file.

The `plugins` option updates all installed plugins not a "specified" one, at least until now

2023-05-15 12:00 UTC, mamaraddio approved these changes

2023-05-15 12:00 UTC, merged